# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 606eb53e9cc9b093ad230aa2598c474594f62e8a287f24e931b9a8d5ac8d30f698f63faddd65e78355abcda222939717108388fabe6ec981a55c6e3a52a02227

test:
  secret_key_base: 6146121b4c650b8006eaffd8b435973d3360ed9168ff43ed93ef9cc2b5c191f5a99a3e5f804d586b9535f52b38d8bdaf7706c69415d58f5d3ea3f44a5ae69dd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
